<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Sales_Order_Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Customers\CustomerSystem.csproj" />
    <ProjectReference Include="..\Order\OrderSystem.csproj" />
    <ProjectReference Include="..\Products\Products.csproj" />
	  <ProjectReference Include="..\Payment\PaymentSystem.csproj" />
  </ItemGroup>

</Project>
